// Code generated by @postbox/sdk-gen; DO NOT EDIT.

package postbox

import "context"

// Client is the unified Postbox client: one key, both planes.
type Client struct {
	c             *client
	Account       *AccountResource
	ApiKeys       *ApiKeysResource
	Domains       *DomainsResource
	Folders       *FoldersResource
	InboundPolicy *InboundPolicyResource
	Logs          *LogsResource
	MailboxGroups *MailboxGroupsResource
	Mailboxes     *MailboxesResource
	Messages      *MessagesResource
	SenderRules   *SenderRulesResource
	Stats         *StatsResource
	Tokens        *TokensResource
	Webhooks      *WebhooksResource
}

// New builds a client from options.
func New(opts Options) (*Client, error) {
	c, err := newClient(opts)
	if err != nil {
		return nil, err
	}
	cl := &Client{c: c}
	cl.Account = &AccountResource{c: c}
	cl.ApiKeys = &ApiKeysResource{c: c}
	cl.Domains = &DomainsResource{c: c}
	cl.Folders = &FoldersResource{c: c}
	cl.InboundPolicy = &InboundPolicyResource{c: c}
	cl.Logs = &LogsResource{c: c}
	cl.MailboxGroups = &MailboxGroupsResource{c: c}
	cl.Mailboxes = &MailboxesResource{c: c}
	cl.Messages = &MessagesResource{c: c}
	cl.SenderRules = &SenderRulesResource{c: c}
	cl.Stats = &StatsResource{c: c}
	cl.Tokens = &TokensResource{c: c}
	cl.Webhooks = &WebhooksResource{c: c}
	return cl, nil
}

// NewWithKey builds a client from just an API key.
func NewWithKey(apiKey string) (*Client, error) { return New(Options{APIKey: apiKey}) }

// Stream opens the server-sent events stream and calls handler per event.
func (cl *Client) Stream(ctx context.Context, handler func(Event) error) error {
	return streamEvents(cl.c, ctx, nil, handler)
}
