// Code generated by @postbox/sdk-gen; DO NOT EDIT.

package postbox

type Account struct {
	Id            string `json:"id"`
	Name          string `json:"name"`
	Slug          string `json:"slug"`
	Plan          string `json:"plan"`
	Status        string `json:"status"`
	BillingActive bool   `json:"billingActive"`
	BillingEmail  string `json:"billingEmail"`
	Region        string `json:"region"`
	OnboardedAt   string `json:"onboardedAt"`
	CreatedAt     string `json:"createdAt"`
}

type ApiKey struct {
	Id          string   `json:"id"`
	KeyPrefix   string   `json:"keyPrefix"`
	Label       string   `json:"label"`
	Permissions []string `json:"permissions"`
	LastUsedAt  string   `json:"lastUsedAt"`
	ExpiresAt   string   `json:"expiresAt"`
	Active      bool     `json:"active"`
}

type BounceRecord struct {
	Id                string `json:"id"`
	TenantId          string `json:"tenantId"`
	ProjectId         string `json:"projectId"`
	ProviderMessageId string `json:"providerMessageId"`
	Address           string `json:"address"`
	BounceType        string `json:"bounceType"`
	BounceCode        string `json:"bounceCode"`
	OriginalFrom      string `json:"originalFrom"`
	OccurredAt        string `json:"occurredAt"`
	Suppressed        bool   `json:"suppressed"`
}

type BouncesPage struct {
	Items      []BounceRecord `json:"items"`
	Total      float64        `json:"total"`
	Page       float64        `json:"page"`
	PageSize   float64        `json:"pageSize"`
	TotalPages float64        `json:"totalPages"`
}

type CreatedApiKey struct {
	Id          string   `json:"id"`
	ApiKey      string   `json:"apiKey"`
	KeyPrefix   string   `json:"keyPrefix"`
	Label       string   `json:"label"`
	Permissions []string `json:"permissions"`
	ExpiresAt   string   `json:"expiresAt"`
	Active      bool     `json:"active"`
}

type DeliverabilityDay struct {
	Id             string  `json:"id"`
	Date           string  `json:"date"`
	SentCount      float64 `json:"sentCount"`
	DeliveredCount float64 `json:"deliveredCount"`
	BouncedCount   float64 `json:"bouncedCount"`
	DeferredCount  float64 `json:"deferredCount"`
	ComplaintCount float64 `json:"complaintCount"`
	DeliveryRate   string  `json:"deliveryRate"`
	BounceRate     string  `json:"bounceRate"`
	ComplaintRate  string  `json:"complaintRate"`
}

type Domain struct {
	Id               string         `json:"id"`
	Domain           string         `json:"domain"`
	Status           string         `json:"status"`
	Region           string         `json:"region"`
	ReceivingEnabled bool           `json:"receivingEnabled"`
	Checks           map[string]any `json:"checks"`
	CreatedAt        string         `json:"createdAt"`
}

type DomainDetail struct {
	Id               string            `json:"id"`
	Domain           string            `json:"domain"`
	Status           string            `json:"status"`
	Region           string            `json:"region"`
	ReceivingEnabled bool              `json:"receivingEnabled"`
	Checks           map[string]any    `json:"checks"`
	CreatedAt        string            `json:"createdAt"`
	Records          []DomainDnsRecord `json:"records"`
	Verification     map[string]any    `json:"verification"`
}

type DomainDnsRecord struct {
	Type     string  `json:"type"`
	Host     string  `json:"host"`
	Value    string  `json:"value"`
	Priority float64 `json:"priority"`
	Purpose  string  `json:"purpose"`
	Optional bool    `json:"optional"`
	Verified bool    `json:"verified"`
}

type Folder struct {
	Id           string  `json:"id"`
	MailboxId    string  `json:"mailboxId"`
	Name         string  `json:"name"`
	SpecialUse   string  `json:"specialUse"`
	MessageCount float64 `json:"messageCount"`
	UnreadCount  float64 `json:"unreadCount"`
}

type InboundPolicy struct {
	Id                string   `json:"id"`
	TenantId          string   `json:"tenantId"`
	ProjectId         string   `json:"projectId"`
	SpamThreshold     string   `json:"spamThreshold"`
	RejectNoSpf       bool     `json:"rejectNoSpf"`
	RejectNoDkim      bool     `json:"rejectNoDkim"`
	DmarcEnforce      bool     `json:"dmarcEnforce"`
	MaxMessageSize    float64  `json:"maxMessageSize"`
	BlockedExtensions []string `json:"blockedExtensions"`
	GreylistEnabled   bool     `json:"greylistEnabled"`
	ActionOnSpam      string   `json:"actionOnSpam"`
	CreatedAt         string   `json:"createdAt"`
	UpdatedAt         string   `json:"updatedAt"`
}

type Mailbox struct {
	Id          string `json:"id"`
	Email       string `json:"email"`
	DisplayName string `json:"displayName"`
	Status      string `json:"status"`
	CreatedAt   string `json:"createdAt"`
}

type MailboxGroup struct {
	Id                 string  `json:"id"`
	TenantId           string  `json:"tenantId"`
	ProjectId          string  `json:"projectId"`
	Name               string  `json:"name"`
	HourlyLimit        float64 `json:"hourlyLimit"`
	DailyLimit         float64 `json:"dailyLimit"`
	BurstLimit         float64 `json:"burstLimit"`
	SpamScoreThreshold string  `json:"spamScoreThreshold"`
	ActionOnSpam       string  `json:"actionOnSpam"`
	RetentionDays      float64 `json:"retentionDays"`
	CreatedAt          string  `json:"createdAt"`
	UpdatedAt          string  `json:"updatedAt"`
}

type MailboxTokenRevocation struct {
	Revoked int64 `json:"revoked"`
}

type Message struct {
	Id              string              `json:"id"`
	TenantId        string              `json:"tenantId"`
	ProjectId       string              `json:"projectId"`
	MailboxId       string              `json:"mailboxId"`
	FolderId        string              `json:"folderId"`
	MessageIdHeader string              `json:"messageIdHeader"`
	ThreadId        string              `json:"threadId"`
	FromAddress     string              `json:"fromAddress"`
	FromName        string              `json:"fromName"`
	ToAddresses     []map[string]any    `json:"toAddresses"`
	CcAddresses     []map[string]any    `json:"ccAddresses"`
	BccAddresses    []map[string]any    `json:"bccAddresses"`
	Subject         string              `json:"subject"`
	BodyText        string              `json:"bodyText"`
	BodyHtml        string              `json:"bodyHtml"`
	SizeBytes       float64             `json:"sizeBytes"`
	HasAttachments  bool                `json:"hasAttachments"`
	Read            bool                `json:"read"`
	Starred         bool                `json:"starred"`
	SpamScore       string              `json:"spamScore"`
	SentAt          string              `json:"sentAt"`
	ReceivedAt      string              `json:"receivedAt"`
	Attachments     []MessageAttachment `json:"attachments"`
}

type MessageAttachment struct {
	Id        string `json:"id"`
	MessageId string `json:"messageId"`
	Filename  string `json:"filename"`
	MimeType  string `json:"mimeType"`
	SizeBytes string `json:"sizeBytes"`
	ContentId string `json:"contentId"`
}

type MessageList struct {
	Messages   []MessageSummary `json:"messages"`
	Threads    []MessageThread  `json:"threads"`
	Pagination map[string]any   `json:"pagination"`
}

type MessageSummary struct {
	Id              string           `json:"id"`
	TenantId        string           `json:"tenantId"`
	ProjectId       string           `json:"projectId"`
	MailboxId       string           `json:"mailboxId"`
	FolderId        string           `json:"folderId"`
	MessageIdHeader string           `json:"messageIdHeader"`
	ThreadId        string           `json:"threadId"`
	FromAddress     string           `json:"fromAddress"`
	FromName        string           `json:"fromName"`
	ToAddresses     []map[string]any `json:"toAddresses"`
	CcAddresses     []map[string]any `json:"ccAddresses"`
	BccAddresses    []map[string]any `json:"bccAddresses"`
	Subject         string           `json:"subject"`
	BodyText        string           `json:"bodyText"`
	BodyHtml        string           `json:"bodyHtml"`
	SizeBytes       float64          `json:"sizeBytes"`
	HasAttachments  bool             `json:"hasAttachments"`
	Read            bool             `json:"read"`
	Starred         bool             `json:"starred"`
	SpamScore       string           `json:"spamScore"`
	SentAt          string           `json:"sentAt"`
	ReceivedAt      string           `json:"receivedAt"`
}

type MessageThread struct {
	Id            string           `json:"id"`
	Subject       string           `json:"subject"`
	From          string           `json:"from"`
	Preview       string           `json:"preview"`
	Ts            string           `json:"ts"`
	Unread        bool             `json:"unread"`
	Starred       bool             `json:"starred"`
	MessagesCount float64          `json:"messagesCount"`
	Messages      []MessageSummary `json:"messages"`
}

type OutboundLog struct {
	Id                string  `json:"id"`
	TenantId          string  `json:"tenantId"`
	ProjectId         string  `json:"projectId"`
	ProviderMessageId string  `json:"providerMessageId"`
	MessageId         string  `json:"messageId"`
	FromAddress       string  `json:"fromAddress"`
	ToAddress         string  `json:"toAddress"`
	Status            string  `json:"status"`
	Attempts          float64 `json:"attempts"`
	LastAttemptAt     string  `json:"lastAttemptAt"`
	NextRetryAt       string  `json:"nextRetryAt"`
	SmtpResponse      string  `json:"smtpResponse"`
	BounceType        string  `json:"bounceType"`
	BounceCode        string  `json:"bounceCode"`
	QueuedAt          string  `json:"queuedAt"`
	SentAt            string  `json:"sentAt"`
	DeliveredAt       string  `json:"deliveredAt"`
}

type OutboundLogsPage struct {
	Items      []OutboundLog `json:"items"`
	Total      float64       `json:"total"`
	Page       float64       `json:"page"`
	PageSize   float64       `json:"pageSize"`
	TotalPages float64       `json:"totalPages"`
}

type OutboundStatus struct {
	MessageId         string  `json:"messageId"`
	Status            string  `json:"status"`
	Terminal          bool    `json:"terminal"`
	ProviderMessageId string  `json:"providerMessageId"`
	Attempts          float64 `json:"attempts"`
	BounceType        string  `json:"bounceType"`
	BounceCode        string  `json:"bounceCode"`
	QueuedAt          string  `json:"queuedAt"`
	SentAt            string  `json:"sentAt"`
	DeliveredAt       string  `json:"deliveredAt"`
}

type SendResult struct {
	MessageId string `json:"messageId"`
	ThreadId  string `json:"threadId"`
}

type SenderRule struct {
	Id        string `json:"id"`
	TenantId  string `json:"tenantId"`
	ProjectId string `json:"projectId"`
	RuleType  string `json:"ruleType"`
	MatchType string `json:"matchType"`
	Value     string `json:"value"`
	Action    string `json:"action"`
	Reason    string `json:"reason"`
	CreatedAt string `json:"createdAt"`
}

type Token struct {
	Id        string `json:"id"`
	Token     string `json:"token"`
	ExpiresAt string `json:"expiresAt"`
}

type TokenRevocation struct {
	Id        string `json:"id"`
	RevokedAt string `json:"revokedAt"`
}

type Usage struct {
	TotalMailboxes        float64        `json:"totalMailboxes"`
	TotalStorageUsedBytes string         `json:"totalStorageUsedBytes"`
	TotalMessagesCount    float64        `json:"totalMessagesCount"`
	Plan                  map[string]any `json:"plan"`
	Limits                map[string]any `json:"limits"`
	Usage                 map[string]any `json:"usage"`
}

type Webhook struct {
	Id     string   `json:"id"`
	Url    string   `json:"url"`
	Events []string `json:"events"`
	Active bool     `json:"active"`
}

type WebhookDelivery struct {
	Id          string         `json:"id"`
	EndpointId  string         `json:"endpointId"`
	EventType   string         `json:"eventType"`
	Payload     map[string]any `json:"payload"`
	Status      string         `json:"status"`
	HttpStatus  float64        `json:"httpStatus"`
	Attempts    float64        `json:"attempts"`
	DeliveredAt string         `json:"deliveredAt"`
	CreatedAt   string         `json:"createdAt"`
}

type AccountUpdateBody struct {
	Name         string `json:"name,omitempty"`
	BillingEmail string `json:"billingEmail,omitempty"`
}

type ApiKeysCreateBody struct {
	Label       string   `json:"label"`
	Permissions []string `json:"permissions,omitempty"`
	ExpiresIn   any      `json:"expiresIn,omitempty"`
}

type DomainsCreateBody struct {
	Domain           string `json:"domain"`
	Region           string `json:"region,omitempty"`
	ReceivingEnabled bool   `json:"receivingEnabled,omitempty"`
}

type FoldersDeleteQuery struct {
	Force string `json:"force,omitempty"`
}

type FoldersUpdateBody struct {
	Name string `json:"name"`
}

type InboundPolicyUpdateBody struct {
	SpamThreshold  float64 `json:"spamThreshold,omitempty"`
	ActionOnSpam   string  `json:"actionOnSpam,omitempty"`
	RejectNoSpf    bool    `json:"rejectNoSpf,omitempty"`
	RejectNoDkim   bool    `json:"rejectNoDkim,omitempty"`
	MaxMessageSize float64 `json:"maxMessageSize,omitempty"`
}

type MailboxGroupsCreateBody struct {
	Name               string  `json:"name"`
	HourlyLimit        float64 `json:"hourlyLimit,omitempty"`
	DailyLimit         float64 `json:"dailyLimit,omitempty"`
	BurstLimit         float64 `json:"burstLimit,omitempty"`
	SpamScoreThreshold float64 `json:"spamScoreThreshold,omitempty"`
	ActionOnSpam       string  `json:"actionOnSpam,omitempty"`
	RetentionDays      float64 `json:"retentionDays,omitempty"`
}

type MailboxGroupsUpdateBody struct {
	Name               string  `json:"name,omitempty"`
	HourlyLimit        float64 `json:"hourlyLimit,omitempty"`
	DailyLimit         float64 `json:"dailyLimit,omitempty"`
	BurstLimit         float64 `json:"burstLimit,omitempty"`
	SpamScoreThreshold float64 `json:"spamScoreThreshold,omitempty"`
	ActionOnSpam       string  `json:"actionOnSpam,omitempty"`
	RetentionDays      float64 `json:"retentionDays,omitempty"`
}

type MailboxesCreateBody struct {
	DomainId    string `json:"domainId"`
	LocalPart   string `json:"localPart"`
	DisplayName string `json:"displayName"`
	Quota       any    `json:"quota,omitempty"`
	GroupId     string `json:"groupId,omitempty"`
}

type MailboxesCreateFolderBody struct {
	Name string `json:"name"`
}

type MailboxesListQuery struct {
	DomainId string `json:"domainId,omitempty"`
}

type MailboxesListMessagesQuery struct {
	Folder   string `json:"folder,omitempty"`
	Read     string `json:"read,omitempty"`
	Starred  string `json:"starred,omitempty"`
	Q        string `json:"q,omitempty"`
	Page     string `json:"page,omitempty"`
	PageSize string `json:"pageSize,omitempty"`
	Threaded string `json:"threaded,omitempty"`
}

type MailboxesUpdateBody struct {
	DisplayName string `json:"displayName,omitempty"`
	Quota       any    `json:"quota,omitempty"`
	Status      any    `json:"status,omitempty"`
	GroupId     string `json:"groupId,omitempty"`
}

type MessagesGetStatusByKeyQuery struct {
	IdempotencyKey string `json:"idempotencyKey"`
}

type MessagesSendBody struct {
	From        string           `json:"from"`
	To          []map[string]any `json:"to"`
	Cc          []map[string]any `json:"cc,omitempty"`
	Bcc         []map[string]any `json:"bcc,omitempty"`
	Subject     string           `json:"subject"`
	BodyText    string           `json:"bodyText,omitempty"`
	BodyHtml    string           `json:"bodyHtml,omitempty"`
	Attachments []map[string]any `json:"attachments,omitempty"`
	ThreadId    string           `json:"threadId,omitempty"`
	ReplyTo     string           `json:"replyTo,omitempty"`
}

type SenderRulesCreateBody struct {
	RuleType  string `json:"ruleType"`
	MatchType string `json:"matchType"`
	Value     string `json:"value"`
	Action    string `json:"action"`
	Reason    string `json:"reason,omitempty"`
}

type SenderRulesListQuery struct {
	Type string `json:"type,omitempty"`
}

type TokensCreateBody struct {
	MailboxId   string   `json:"mailboxId"`
	Permissions []string `json:"permissions"`
	ExpiresIn   any      `json:"expiresIn,omitempty"`
}

type WebhooksCreateBody struct {
	Url    string   `json:"url"`
	Secret string   `json:"secret"`
	Events []string `json:"events,omitempty"`
	Active bool     `json:"active,omitempty"`
}

type WebhooksUpdateBody struct {
	Url    string   `json:"url,omitempty"`
	Secret string   `json:"secret,omitempty"`
	Events []string `json:"events,omitempty"`
	Active bool     `json:"active,omitempty"`
}
