// Code generated by @postbox/sdk-gen; DO NOT EDIT.

package postbox

import "context"

type AccountResource struct{ c *client }

// Get GET /account
func (r *AccountResource) Get(ctx context.Context) (*Account, error) {
	return do[*Account](r.c, ctx, "GET", "/account", nil, nil, "")
}

// Update PATCH /account
func (r *AccountResource) Update(ctx context.Context, body *AccountUpdateBody) (*Account, error) {
	return do[*Account](r.c, ctx, "PATCH", "/account", nil, body, "")
}

type ApiKeysResource struct{ c *client }

// Create POST /api-keys
func (r *ApiKeysResource) Create(ctx context.Context, body *ApiKeysCreateBody) (*CreatedApiKey, error) {
	return do[*CreatedApiKey](r.c, ctx, "POST", "/api-keys", nil, body, "")
}

// Delete DELETE /api-keys/{id}
func (r *ApiKeysResource) Delete(ctx context.Context, id string) (any, error) {
	return do[any](r.c, ctx, "DELETE", "/api-keys/"+id, nil, nil, "")
}

// List GET /api-keys
func (r *ApiKeysResource) List(ctx context.Context) ([]ApiKey, error) {
	return do[[]ApiKey](r.c, ctx, "GET", "/api-keys", nil, nil, "")
}

type DomainsResource struct{ c *client }

// Create POST /domains
func (r *DomainsResource) Create(ctx context.Context, body *DomainsCreateBody) (*DomainDetail, error) {
	return do[*DomainDetail](r.c, ctx, "POST", "/domains", nil, body, "")
}

// Delete DELETE /domains/{id}
func (r *DomainsResource) Delete(ctx context.Context, id string) (any, error) {
	return do[any](r.c, ctx, "DELETE", "/domains/"+id, nil, nil, "")
}

// Get GET /domains/{id}
func (r *DomainsResource) Get(ctx context.Context, id string) (*DomainDetail, error) {
	return do[*DomainDetail](r.c, ctx, "GET", "/domains/"+id, nil, nil, "")
}

// List GET /domains
func (r *DomainsResource) List(ctx context.Context) ([]Domain, error) {
	return do[[]Domain](r.c, ctx, "GET", "/domains", nil, nil, "")
}

// ListRecords GET /domains/{id}/records
func (r *DomainsResource) ListRecords(ctx context.Context, id string) ([]DomainDnsRecord, error) {
	return do[[]DomainDnsRecord](r.c, ctx, "GET", "/domains/"+id+"/records", nil, nil, "")
}

// Verify POST /domains/{id}/verify
func (r *DomainsResource) Verify(ctx context.Context, id string) (*DomainDetail, error) {
	return do[*DomainDetail](r.c, ctx, "POST", "/domains/"+id+"/verify", nil, nil, "")
}

type FoldersResource struct{ c *client }

// Delete DELETE /folders/{id}
func (r *FoldersResource) Delete(ctx context.Context, id string, query *FoldersDeleteQuery) (any, error) {
	return do[any](r.c, ctx, "DELETE", "/folders/"+id, query, nil, "")
}

// Update PATCH /folders/{id}
func (r *FoldersResource) Update(ctx context.Context, id string, body *FoldersUpdateBody) (*Folder, error) {
	return do[*Folder](r.c, ctx, "PATCH", "/folders/"+id, nil, body, "")
}

type InboundPolicyResource struct{ c *client }

// Get GET /inbound-policy/inbound
func (r *InboundPolicyResource) Get(ctx context.Context) (*InboundPolicy, error) {
	return do[*InboundPolicy](r.c, ctx, "GET", "/inbound-policy/inbound", nil, nil, "")
}

// Update PATCH /inbound-policy/inbound
func (r *InboundPolicyResource) Update(ctx context.Context, body *InboundPolicyUpdateBody) (*InboundPolicy, error) {
	return do[*InboundPolicy](r.c, ctx, "PATCH", "/inbound-policy/inbound", nil, body, "")
}

type LogsResource struct{ c *client }

// Outbound GET /logs/outbound
func (r *LogsResource) Outbound(ctx context.Context) (*OutboundLogsPage, error) {
	return do[*OutboundLogsPage](r.c, ctx, "GET", "/logs/outbound", nil, nil, "")
}

type MailboxGroupsResource struct{ c *client }

// Create POST /mailbox-groups
func (r *MailboxGroupsResource) Create(ctx context.Context, body *MailboxGroupsCreateBody) (*MailboxGroup, error) {
	return do[*MailboxGroup](r.c, ctx, "POST", "/mailbox-groups", nil, body, "")
}

// Delete DELETE /mailbox-groups/{id}
func (r *MailboxGroupsResource) Delete(ctx context.Context, id string) (any, error) {
	return do[any](r.c, ctx, "DELETE", "/mailbox-groups/"+id, nil, nil, "")
}

// Get GET /mailbox-groups/{id}
func (r *MailboxGroupsResource) Get(ctx context.Context, id string) (*MailboxGroup, error) {
	return do[*MailboxGroup](r.c, ctx, "GET", "/mailbox-groups/"+id, nil, nil, "")
}

// List GET /mailbox-groups
func (r *MailboxGroupsResource) List(ctx context.Context) ([]MailboxGroup, error) {
	return do[[]MailboxGroup](r.c, ctx, "GET", "/mailbox-groups", nil, nil, "")
}

// Update PATCH /mailbox-groups/{id}
func (r *MailboxGroupsResource) Update(ctx context.Context, id string, body *MailboxGroupsUpdateBody) (*MailboxGroup, error) {
	return do[*MailboxGroup](r.c, ctx, "PATCH", "/mailbox-groups/"+id, nil, body, "")
}

type MailboxesResource struct{ c *client }

// Create POST /mailboxes
func (r *MailboxesResource) Create(ctx context.Context, body *MailboxesCreateBody) (*Mailbox, error) {
	return do[*Mailbox](r.c, ctx, "POST", "/mailboxes", nil, body, "")
}

// CreateFolder POST /mailboxes/{id}/folders
func (r *MailboxesResource) CreateFolder(ctx context.Context, id string, body *MailboxesCreateFolderBody) (*Folder, error) {
	return do[*Folder](r.c, ctx, "POST", "/mailboxes/"+id+"/folders", nil, body, "")
}

// Delete DELETE /mailboxes/{id}
func (r *MailboxesResource) Delete(ctx context.Context, id string) (any, error) {
	return do[any](r.c, ctx, "DELETE", "/mailboxes/"+id, nil, nil, "")
}

// Get GET /mailboxes/{id}
func (r *MailboxesResource) Get(ctx context.Context, id string) (*Mailbox, error) {
	return do[*Mailbox](r.c, ctx, "GET", "/mailboxes/"+id, nil, nil, "")
}

// List GET /mailboxes
func (r *MailboxesResource) List(ctx context.Context, query *MailboxesListQuery) ([]Mailbox, error) {
	return do[[]Mailbox](r.c, ctx, "GET", "/mailboxes", query, nil, "")
}

// ListFolders GET /mailboxes/{id}/folders
func (r *MailboxesResource) ListFolders(ctx context.Context, id string) ([]Folder, error) {
	return do[[]Folder](r.c, ctx, "GET", "/mailboxes/"+id+"/folders", nil, nil, "")
}

// ListMessages GET /mailboxes/{id}/messages
func (r *MailboxesResource) ListMessages(ctx context.Context, id string, query *MailboxesListMessagesQuery) (*MessageList, error) {
	return do[*MessageList](r.c, ctx, "GET", "/mailboxes/"+id+"/messages", query, nil, "")
}

// Tokens DELETE /mailboxes/{mailboxId}/tokens
func (r *MailboxesResource) Tokens(ctx context.Context, mailboxId string) (*MailboxTokenRevocation, error) {
	return do[*MailboxTokenRevocation](r.c, ctx, "DELETE", "/mailboxes/"+mailboxId+"/tokens", nil, nil, "")
}

// Update PATCH /mailboxes/{id}
func (r *MailboxesResource) Update(ctx context.Context, id string, body *MailboxesUpdateBody) (*Mailbox, error) {
	return do[*Mailbox](r.c, ctx, "PATCH", "/mailboxes/"+id, nil, body, "")
}

type MessagesResource struct{ c *client }

// Delete DELETE /messages/{id}
func (r *MessagesResource) Delete(ctx context.Context, id string) (any, error) {
	return do[any](r.c, ctx, "DELETE", "/messages/"+id, nil, nil, "")
}

// Get GET /messages/{id}
func (r *MessagesResource) Get(ctx context.Context, id string) (*Message, error) {
	return do[*Message](r.c, ctx, "GET", "/messages/"+id, nil, nil, "")
}

// GetStatus GET /messages/{id}/status
func (r *MessagesResource) GetStatus(ctx context.Context, id string) (*OutboundStatus, error) {
	return do[*OutboundStatus](r.c, ctx, "GET", "/messages/"+id+"/status", nil, nil, "")
}

// GetStatusByKey GET /messages/status
func (r *MessagesResource) GetStatusByKey(ctx context.Context, query *MessagesGetStatusByKeyQuery) (*OutboundStatus, error) {
	return do[*OutboundStatus](r.c, ctx, "GET", "/messages/status", query, nil, "")
}

// Send POST /messages/send
func (r *MessagesResource) Send(ctx context.Context, body *MessagesSendBody) (*SendResult, error) {
	return do[*SendResult](r.c, ctx, "POST", "/messages/send", nil, body, "")
}

type SenderRulesResource struct{ c *client }

// Create POST /sender-rules/rules
func (r *SenderRulesResource) Create(ctx context.Context, body *SenderRulesCreateBody) (*SenderRule, error) {
	return do[*SenderRule](r.c, ctx, "POST", "/sender-rules/rules", nil, body, "")
}

// Delete DELETE /sender-rules/rules/{id}
func (r *SenderRulesResource) Delete(ctx context.Context, id string) (any, error) {
	return do[any](r.c, ctx, "DELETE", "/sender-rules/rules/"+id, nil, nil, "")
}

// List GET /sender-rules/rules
func (r *SenderRulesResource) List(ctx context.Context, query *SenderRulesListQuery) ([]SenderRule, error) {
	return do[[]SenderRule](r.c, ctx, "GET", "/sender-rules/rules", query, nil, "")
}

type StatsResource struct{ c *client }

// Bounces GET /stats/bounces
func (r *StatsResource) Bounces(ctx context.Context) (*BouncesPage, error) {
	return do[*BouncesPage](r.c, ctx, "GET", "/stats/bounces", nil, nil, "")
}

// Deliverability GET /stats/deliverability
func (r *StatsResource) Deliverability(ctx context.Context) ([]DeliverabilityDay, error) {
	return do[[]DeliverabilityDay](r.c, ctx, "GET", "/stats/deliverability", nil, nil, "")
}

// Usage GET /stats/usage
func (r *StatsResource) Usage(ctx context.Context) (*Usage, error) {
	return do[*Usage](r.c, ctx, "GET", "/stats/usage", nil, nil, "")
}

type TokensResource struct{ c *client }

// Create POST /tokens
func (r *TokensResource) Create(ctx context.Context, body *TokensCreateBody) (*Token, error) {
	return do[*Token](r.c, ctx, "POST", "/tokens", nil, body, "")
}

// Revoke POST /tokens/{id}/revoke
func (r *TokensResource) Revoke(ctx context.Context, id string) (*TokenRevocation, error) {
	return do[*TokenRevocation](r.c, ctx, "POST", "/tokens/"+id+"/revoke", nil, nil, "")
}

type WebhooksResource struct{ c *client }

// Create POST /webhooks
func (r *WebhooksResource) Create(ctx context.Context, body *WebhooksCreateBody) (*Webhook, error) {
	return do[*Webhook](r.c, ctx, "POST", "/webhooks", nil, body, "")
}

// Delete DELETE /webhooks/{id}
func (r *WebhooksResource) Delete(ctx context.Context, id string) (any, error) {
	return do[any](r.c, ctx, "DELETE", "/webhooks/"+id, nil, nil, "")
}

// List GET /webhooks
func (r *WebhooksResource) List(ctx context.Context) ([]Webhook, error) {
	return do[[]Webhook](r.c, ctx, "GET", "/webhooks", nil, nil, "")
}

// ListDeliveries GET /webhooks/{id}/deliveries
func (r *WebhooksResource) ListDeliveries(ctx context.Context, id string) ([]WebhookDelivery, error) {
	return do[[]WebhookDelivery](r.c, ctx, "GET", "/webhooks/"+id+"/deliveries", nil, nil, "")
}

// Update PATCH /webhooks/{id}
func (r *WebhooksResource) Update(ctx context.Context, id string, body *WebhooksUpdateBody) (*Webhook, error) {
	return do[*Webhook](r.c, ctx, "PATCH", "/webhooks/"+id, nil, body, "")
}
